//! Fails when any source file exceeds the line limit.
//!
//! Large files resist the modular, easy-to-extend structure the project targets, so the
//! limit is enforced in CI. Every hand-written source counts, including scripts without an
//! extension; only lockfiles and build output are exempt. Data files (JSON locale bundles,
//! XML fixtures, Markdown) are not source code.

use std::{collections::BTreeSet, path::Path, process::Command};

use anyhow::{Context, Result, bail};

pub const MAX_LINES: usize = 600;

const SOURCE_EXTENSIONS: &[&str] = &[
    "rs", "ts", "tsx", "mts", "cts", "js", "jsx", "mjs", "cjs", "vue", "css", "scss", "html", "sh",
    "bash", "ps1", "psm1", "py", "yml", "yaml", "toml",
];

/// Generated by package managers, never edited by hand.
const LOCKFILES: &[&str] = &[
    "Cargo.lock",
    "pnpm-lock.yaml",
    "package-lock.json",
    "yarn.lock",
];

/// Build output that may exist in a checkout but is not source.
const OUTPUT_DIRS: &[&str] = &["module/webroot/", "target/"];

pub fn run(repo_root: &Path) -> Result<()> {
    let mut offenders = Vec::new();
    let mut checked = 0usize;

    for path in candidate_files(repo_root)? {
        if is_exempt(&path) {
            continue;
        }
        // Deleted or binary files are not source.
        let Ok(contents) = std::fs::read_to_string(repo_root.join(&path)) else {
            continue;
        };
        if !is_source(&path, &contents) {
            continue;
        }
        checked += 1;
        let lines = contents.lines().count();
        if lines > MAX_LINES {
            offenders.push((path, lines));
        }
    }

    if offenders.is_empty() {
        println!("line-limit: {checked} source files, all within {MAX_LINES} lines");
        return Ok(());
    }

    offenders.sort_by_key(|(_, lines)| std::cmp::Reverse(*lines));
    eprintln!(
        "line-limit: {} file(s) exceed {MAX_LINES} lines:",
        offenders.len()
    );
    for (path, lines) in &offenders {
        eprintln!("  {lines:>5}  {path}");
    }
    bail!("split these files so every source file stays within {MAX_LINES} lines");
}

/// Tracked files plus new files that are not ignored, so the check also works before `git add`.
fn candidate_files(repo_root: &Path) -> Result<BTreeSet<String>> {
    let output = Command::new("git")
        .args([
            "ls-files",
            "-z",
            "--cached",
            "--others",
            "--exclude-standard",
        ])
        .current_dir(repo_root)
        .output()
        .context("run `git ls-files`")?;
    if !output.status.success() {
        bail!(
            "`git ls-files` failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    Ok(String::from_utf8_lossy(&output.stdout)
        .split('\0')
        .filter(|path| !path.is_empty())
        .map(str::to_owned)
        .collect())
}

fn is_source(path: &str, contents: &str) -> bool {
    match Path::new(path).extension().and_then(|value| value.to_str()) {
        Some(ext) => SOURCE_EXTENSIONS.contains(&ext.to_ascii_lowercase().as_str()),
        None => contents.starts_with("#!"),
    }
}

fn is_exempt(path: &str) -> bool {
    let name = path.rsplit('/').next().unwrap_or(path);
    LOCKFILES.contains(&name) || OUTPUT_DIRS.iter().any(|dir| path.starts_with(dir))
}

#[cfg(test)]
mod tests {
    use super::{is_exempt, is_source};

    #[test]
    fn counts_every_kind_of_source() {
        for path in [
            "crates/duck-core/src/lib.rs",
            "ui/src/App.vue",
            "ui/scripts/import-tricky-addon-locales.mjs",
            "ui/index.html",
            ".github/workflows/ci.yml",
            "module/customize.sh",
            "scripts/build.ps1",
            "Cargo.toml",
        ] {
            assert!(is_source(path, ""), "{path}");
        }
    }

    #[test]
    fn counts_scripts_without_an_extension() {
        assert!(is_source(
            "module/META-INF/com/google/android/update-binary",
            "#!/sbin/sh\n"
        ));
        assert!(!is_source("LICENSE", "MIT License\n"));
    }

    #[test]
    fn skips_data_files() {
        assert!(!is_source("README.md", ""));
        assert!(!is_source("ui/src/features/rkp/locales/en.json", ""));
        assert!(!is_source(
            "crates/duck-tricky-store/assets/aosp-keybox.xml",
            ""
        ));
    }

    #[test]
    fn exempts_only_lockfiles_and_build_output() {
        assert!(is_exempt("ui/pnpm-lock.yaml"));
        assert!(is_exempt("Cargo.lock"));
        assert!(is_exempt("module/webroot/assets/index.js"));
        assert!(!is_exempt("ui/src/components/ui/button/index.ts"));
        assert!(!is_exempt("crates/duck-tricky-store/src/assets.rs"));
    }
}
