import pluginVitest from "@vitest/eslint-plugin"
import skipFormatting from "@vue/eslint-config-prettier/skip-formatting"
import { defineConfigWithVueTs, vueTsConfigs } from "@vue/eslint-config-typescript"
import boundaries from "eslint-plugin-boundaries"
import pluginVue from "eslint-plugin-vue"
import { globalIgnores } from "eslint/config"

// Layers of the WebUI. Each folder under src/features is its own element, so features can
// only reach each other through contributions registered with the core, never by import.
const elements = [
  { type: "app", pattern: "src/app" },
  { type: "core", pattern: "src/core" },
  { type: "ui", pattern: "src/components" },
  { type: "lib", pattern: "src/lib" },
  { type: "feature", pattern: "src/features/*", capture: ["name"] },
  { type: "dev", pattern: "src/dev" },
] as const

export default defineConfigWithVueTs(
  {
    name: "app/files-to-lint",
    files: ["**/*.{ts,mts,vue}"],
  },

  // Generated by the shadcn-vue CLI, then restyled for Material 3 Expressive: merge updates
  // from `shadcn-vue add` by hand instead of overwriting.
  globalIgnores([
    "**/dist/**",
    "dist-e2e/**",
    "**/coverage/**",
    "src/components/ui/**",
    "playwright-report/**",
    "test-results/**",
  ]),

  pluginVue.configs["flat/recommended"],
  vueTsConfigs.recommended,

  {
    ...pluginVitest.configs.recommended,
    files: ["src/**/*.test.ts"],
  },

  {
    name: "app/rules",
    rules: {
      // Mirrors the repository-wide 600-line gate so editors flag it early.
      "max-lines": ["error", { max: 600, skipBlankLines: false, skipComments: false }],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { ignoreRestSiblings: true, argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  {
    name: "app/boundaries",
    files: ["src/**/*.{ts,vue}"],
    plugins: { boundaries },
    settings: {
      "boundaries/elements": elements,
      "boundaries/files": [{ pattern: "src/*.{ts,vue}", category: "entry" }],
      "import/resolver": { typescript: { alwaysTryTypes: true } },
    },
    rules: {
      "boundaries/dependencies": [
        "error",
        {
          default: "disallow",
          // Also evaluate package imports, so the kernelsu-alt policy below applies.
          checkAllOrigins: true,
          policies: [
            { allow: { dependency: { relationship: { to: "internal" } } } },
            { allow: { to: { module: { origin: ["external", "core"] } } } },
            {
              from: { file: { categories: "entry" } },
              allow: {
                to: [
                  { element: { types: ["app", "core", "dev", "lib", "ui"] } },
                  { file: { categories: "entry" } },
                ],
              },
            },
            { from: { element: { type: "dev" } }, allow: { to: { element: { type: "core" } } } },
            {
              from: { element: { type: "app" } },
              allow: { to: { element: { types: ["core", "lib", "ui"] } } },
            },
            {
              from: { element: { type: "core" } },
              allow: { to: { element: { types: ["lib", "ui"] } } },
            },
            {
              from: { element: { type: "feature" } },
              allow: { to: { element: { types: ["core", "lib", "ui"] } } },
            },
            { from: { element: { type: "ui" } }, allow: { to: { element: { type: "lib" } } } },
            {
              // The KernelSU JavaScript bridge is wrapped once in core/bridge so an API
              // change in the manager or the library touches a single module.
              from: { element: { type: "!core" } },
              disallow: { to: { module: { origin: "external", source: "kernelsu-alt" } } },
            },
          ],
        },
      ],
    },
  },

  skipFormatting,
)
